project:
  type: website
  output-dir: docs
  
website:
  title: "MiniProject3"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - MiniProject1.qmd
      - MiniProject2.qmd
      - SentimentAnalysis.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

